import Authprovider from "@/components/Authprovider/Authprovider";
import "./globals.css";
import { Header } from "@/components/Header";
import { PostsProvider } from "./context/PostsContext";
import { ToastContainer } from "react-toastify";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Authprovider>
          <PostsProvider>
            <ToastContainer />
            <Header />
            {children}
          </PostsProvider>
        </Authprovider>

        {/* Load Flowbite script asynchronously */}
        <Script
          src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
